[2021-02-16 12:11:29,469] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_2 2021-02-14T00:00:00+00:00 [queued]>
[2021-02-16 12:11:30,512] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_2 2021-02-14T00:00:00+00:00 [queued]>
[2021-02-16 12:11:30,516] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-16 12:11:30,528] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-16 12:11:30,543] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-16 12:11:30,947] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_2> on 2021-02-14T00:00:00+00:00
[2021-02-16 12:11:31,015] {standard_task_runner.py:52} INFO - Started process 60 to run task
[2021-02-16 12:11:31,090] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_2', '2021-02-14T00:00:00+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmp43qh50re', '--error-file', '/tmp/tmp398rbu7o']
[2021-02-16 12:11:31,092] {standard_task_runner.py:77} INFO - Job 11: Subtask runme_2
[2021-02-16 12:11:33,032] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_2 2021-02-14T00:00:00+00:00 [running]> on host 071a2d8d0e8e
[2021-02-16 12:11:34,582] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_2
AIRFLOW_CTX_EXECUTION_DATE=2021-02-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-14T00:00:00+00:00
[2021-02-16 12:11:34,733] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-02-16 12:11:34,750] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_2__20210214" && sleep 1
[2021-02-16 12:11:35,044] {bash.py:169} INFO - Output:
[2021-02-16 12:11:35,078] {bash.py:173} INFO - example_bash_operator__runme_2__20210214
[2021-02-16 12:11:36,116] {bash.py:177} INFO - Command exited with return code 0
[2021-02-16 12:11:36,544] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_2, execution_date=20210214T000000, start_date=20210216T121129, end_date=20210216T121136
[2021-02-16 12:11:37,011] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-16 12:11:37,046] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-02-16 12:11:37,132] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 60
[2021-02-16 12:11:37,212] {process_utils.py:66} INFO - Process psutil.Process(pid=60, status='terminated', exitcode=0, started='12:11:30') (60) terminated with exit code 0
